apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ih1cqfa78-python 
  janus-idp.io/tekton: ih1cqfa78-python
  backstage.io/kubernetes-id: ih1cqfa78-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ih1cqfa78-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml